-- SourcingOS V17.3 Candidate Graph persistence schema for Supabase/Postgres
create table if not exists candidates (id text primary key, canonical_name text not null, headline text, location text, status text not null default 'needs_review', match_score integer default 0, evidence_count integer default 0, contact_signal_count integer default 0, refresh_policy jsonb not null default '{}'::jsonb, next_refresh_at timestamptz, last_refreshed_at timestamptz, payload jsonb not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists source_profiles (id text primary key, candidate_id text references candidates(id) on delete cascade, source text not null, source_profile_id text not null, display_name text not null, headline text, location text, organization text, profile_url text, skills jsonb not null default '[]'::jsonb, evidence jsonb not null default '[]'::jsonb, contact_signals jsonb not null default '[]'::jsonb, identity_signals jsonb not null default '[]'::jsonb, payload jsonb not null, refreshed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(source, source_profile_id));
create table if not exists identity_match_reviews (id text primary key, candidate_id text references candidates(id) on delete cascade, source_profile_ids jsonb not null, score integer not null, reasons jsonb not null default '[]'::jsonb, decision text not null default 'pending', decided_by text, decided_at timestamptz, created_at timestamptz not null default now(), constraint no_system_auto_merge check (decision in ('pending','confirmed','rejected')));
create table if not exists candidate_refresh_events (id bigserial primary key, candidate_id text references candidates(id) on delete set null, event_type text not null, detail text not null, payload jsonb, created_at timestamptz not null default now());
create index if not exists idx_candidates_updated_at on candidates(updated_at desc);
create index if not exists idx_candidates_next_refresh_at on candidates(next_refresh_at);
create index if not exists idx_source_profiles_candidate_id on source_profiles(candidate_id);
create index if not exists idx_source_profiles_source on source_profiles(source);
