'use client'
import { useMemo, useState } from 'react'
import { trackClientEvent } from '@/lib/analytics'
function hits(text:string, words:string[]){ const low=text.toLowerCase(); return words.filter(w=>low.includes(w.toLowerCase())) }
const titleSeeds=['Software Engineer','Platform Engineer','DevSecOps Engineer','Machine Learning Engineer','Data Engineer','Security Engineer','ISSO','Registered Nurse','Cloud Engineer','Systems Engineer','MLOps Engineer']
const skills=['Kubernetes','Terraform','Docker','CI/CD','AWS GovCloud','Python','PyTorch','RAG','LLM','RMF','ATO','NIST','FedRAMP','Epic','BLS','ACLS','Snowflake','dbt','Airflow','Splunk','SIEM']
export function JDStrategyTool(){
 const [jd,setJd]=useState('Senior DevSecOps Engineer with TS/SCI, AWS GovCloud, Terraform, Kubernetes, Docker, CI/CD, Linux, Python, RMF, ATO, NIST, FedRAMP, and DoD delivery experience.')
 const strategy=useMemo(()=>{ const titles=hits(jd,titleSeeds); const must=hits(jd,skills); const lanes=[`Direct fit: ${titles.slice(0,3).join(' / ')||'primary title variants'} + ${must.slice(0,5).join(', ')}`,`Adjacent title lane: broaden into Platform, Cloud, Systems, SRE, and domain-adjacent titles`,`Evidence lane: search GitHub, Stack Overflow, OpenAlex, or registry sources for proof signals`,`Donor company lane: target companies likely to produce this talent`,`Rediscovery lane: search old ATS/CRM notes for overlapping evidence`]; const questions=['Which requirements are truly must-have?','What evidence would make you confident enough for a screen?','Which titles have produced good hires before?','What should loosen first if the pool is too small?','Which companies are positive or negative donor signals?']; return {titles,must,lanes,questions} },[jd])
 const md=`# SourcingOS Source Pack\n\n## Role notes\n${jd}\n\n## Target titles\n${strategy.titles.join(', ')||'Add target titles'}\n\n## Must-have signals\n${strategy.must.join(', ')||'Add must-have evidence'}\n\n## Search lanes\n${strategy.lanes.map(x=>'- '+x).join('\n')}\n\n## HM calibration questions\n${strategy.questions.map(x=>'- '+x).join('\n')}`
 function download(){ const u=URL.createObjectURL(new Blob([md],{type:'text/markdown'})); const a=document.createElement('a'); a.href=u; a.download='sourcingos-source-pack.md'; a.click(); URL.revokeObjectURL(u); trackClientEvent('download_source_pack') }
 return <div className="interactive-tool"><label>Paste JD or role notes</label><textarea className="textarea big" value={jd} onChange={e=>setJd(e.target.value)} /><div className="grid two"><div className="result-card"><h3>Search lanes</h3>{strategy.lanes.map(x=><p key={x}>• {x}</p>)}</div><div className="result-card"><h3>HM calibration questions</h3>{strategy.questions.map(x=><p key={x}>• {x}</p>)}</div></div><button className="btn" onClick={download}>Download source pack</button></div>
}
